---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./synology-csi.yaml
  - ./test-secret.sops.yaml
configMapGenerator:
  - name: synology-csi-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml