apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:PonNem3Y3TwbAghBG+y6wE1YOCXR6L/voPRF0ESlyVgS0v0s2hDGJWmutRrihA6KshWw8brohAFdNTQ6BtXfo9AY3PAL1Tf6wG5MSVLNdrOW,iv:s0qgWJOt3zMJe9TjrDmNcLcAv4326Ken5VBgXS4Ee+A=,tag:OaMLH2pBO+pnWRBe9SsoOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uec9202vfs5uykrmnfnx756asatjk297r9t4sm5zqm8fywlsna6qc240ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNEdxdllzeVR3NWNDWDZn
            RE80ZTBnd2lDUXZDMlFpazlmdXkzQ3RodENNCkNULzJFT0dBSStZRUdVWjlYZWtq
            d0FKdDBxNmVHV2FkUjduanhwNG1GbGsKLS0tIFNvZWg5TW8rbHRhUHUxcmV1VERE
            cS9KZWFOWVFwejNnTTFNTTVQSVBHaGsKxhFImIbRiANFxx9JnVidOX1HzLQyCm5h
            q2lPuV4HJ5GxoCyVuSSVKXVDUNH2v/ASb6a5Ae+njjcIomkXgXCHVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T10:07:48Z"
    mac: ENC[AES256_GCM,data:gUKWIscmajtc+VOK264A6ViJ3UjMFdqvGBGuQmERGiziZhUSc6n+NYss/oA3H2/233CYPfT2J0nI5gCbjfcrEOI422F2zhnB1RnWeRJAINrmUPT+LDUljpJnOia4w4fNzQIXj/XgibVxK9JlVIsG4+AOaQyK/GO1hX1gy571eYE=,iv:2Q16Q633nmHuZLRGLngp/98X2dPk9LDMnhMIIbDUV1I=,tag:9vDYva932L6UgRXcIXcW+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
